### ISSUE TITLE
Cant generate site correctly.

### ISSUE THREAD

**Issue by flamura** [kamikat/jekyll-theme-kagami#2]
It doesn't generate the assets folder in _site.
Here is the index.html.
```html
<!DOCTYPE html>
<html lang="en">
  <head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Your awesome title</title>
  <meta name="description" content="Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search resu...">

  
  <link rel="stylesheet" href="/assets/styles/core.css?v=20170919130315">
  <link rel="stylesheet" href="/assets/styles/fontello.css?v=20170919130315">
  <link rel="stylesheet" href="/assets/styles/highlighting/default.css?v=20170919130315">

  <link rel="canonical" href="http://localhost:4000/">
  <link rel="alternate" type="application/rss+xml" title="Your awesome title" href="/feed.xml">

  

  
</head>

  


</html>
```

ruby version:ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu] (from apt)
jekyll version:jekyll 3.5.2
system:Debian buster.

To reproduce it
```
jekyll new foo
cd foo
sed -i 's/minima/jekyll-theme-kagami/' _config.yml
echo gem \"jekyll-theme-kagami\" >>Gemfile
bundle install --path vendor/bundle
bundle exec jekyll s
```

Thank you.:D

**Comment by kamikat** [comment]
Thanks for issue report. `assets/` folder is listed to be part of gem package now. Update of 0.1.11 should be available later tonight :P

**Comment by kamikat** [comment]
Updated.

**Comment by flamura** [comment]
Thanks. `assets` issue is solved!

**Comment by flamura** [comment]
There is no content in `/` by default. (No body in the HTML). It would be better if you mentioned `change the layout in index.md to 'post-list' instead of 'home'` in README. 😋

**Comment by amyszczepanski** [comment]
I had this same problem. I was able to fix it by following the advice in the above comment and editing the index.md file. Could this advice be added to the README file?

Is there more detailed documentation available? For example, the sample screenshots show a header image, but there is no explanation of how or where to add one.

**Comment by kamikat** [comment]
@amyszczepanski Ahhh, I forgot to release these changes. Just fixed. 

The example posts are generated from `example/_posts` folder, just check it :D
