### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by AparnaAnna** [kamikat/jekyll-theme-kagami#5]
Hi there

Thank you for your jekyll theme

I've downloaded the gem and unpacked from this site: https://rubygems.org/gems/jekyll-theme-kagami/versions/0.1.12, but i can't for the file of me find the _config.yml file.

Any ideas?

regards

Ben

**Comment by kamikat** [comment]
Maybe you should [setup a jekyll site project](https://jekyllrb.com/docs/#instructions) before install data from the package.
