### ISSUE TITLE
Jekyll 4

### ISSUE THREAD

**Issue by einarmagnus** [kamikat/jekyll-theme-kagami#6]
The plugin is declared as not working with jekyll 4. 
When I fork it and just bump the version number it seems to work though. Maybe you can just change the gemspec?

```
Bundler could not find compatible versions for gem "jekyll":
  In snapshot (Gemfile.lock):
    jekyll (= 4.0.0)

  In Gemfile:
    jekyll (~> 4.0.0)

    jekyll-theme-kagami was resolved to 0.1.12, which depends on
      jekyll (~> 3.3)
```

**Comment by kamikat** [comment]
Runtime dependency to `jekyll` has been dropped for development dependency to `github-pages` in [gemspec](https://github.com/kamikat/jekyll-theme-kagami/blob/master/jekyll-theme-kagami.gemspec). 

Tthis problem should be fixed in the upcoming release.
