### ISSUE TITLE
Question regarding the setting of the page

### ISSUE THREAD

**Issue by KingJacM** [kamikat/jekyll-theme-kagami#7]
Hello:

Could you tell me how did you make the head banner full width whilst limit the body's width at the same time?

I'm a beginner so I inspected your website but still don't quite get it. @kamikat 

![image](https://user-images.githubusercontent.com/26500506/79316735-dbd15480-7f58-11ea-9be2-469b363ca8d6.png)

Thank you

**Comment by kamikat** [comment]
It's implemented by centering `.post-cover` box of 100vw.
https://github.com/kamikat/jekyll-theme-kagami/blob/05fd237d5a8012e82a9fde0ef753947af114615d/_sass/kagami/_typography.scss#L150-L169
