### ISSUE TITLE
installation failure

### ISSUE THREAD

**Issue by lovelynl** [kamikat/jekyll-theme-kagami#9]
I am trying to run this line to install: 

gem install jekyll-theme-kagami

The error msg poped up: 
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.3.0 directory.

How to fix this issue? Thank you.

**Comment by kamikat** [comment]
It seems that you're using system ruby binary.

Check [rbenv](https://github.com/rbenv/rbenv) to setup a virtual environment and run the `gem` command in a virtual environment.
